//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3053 版自动生成。
// 
namespace BarCode.DataService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DataService() {
            this.Url = "http://200.200.200.200/BarCode/Service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnClass CheckUser(string userid, string password, string server, string database) {
            object[] results = this.Invoke("CheckUser", new object[] {
                        userid,
                        password,
                        server,
                        database});
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckUser(string userid, string password, string server, string database, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckUser", new object[] {
                        userid,
                        password,
                        server,
                        database}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReturnClass EndCheckUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnClass GetData(string selectCmd, string userid, string password, string server, string database) {
            object[] results = this.Invoke("GetData", new object[] {
                        selectCmd,
                        userid,
                        password,
                        server,
                        database});
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetData(string selectCmd, string userid, string password, string server, string database, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetData", new object[] {
                        selectCmd,
                        userid,
                        password,
                        server,
                        database}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReturnClass EndGetData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Execute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnClass Execute(string commandstr, string userid, string password, string server, string database) {
            object[] results = this.Invoke("Execute", new object[] {
                        commandstr,
                        userid,
                        password,
                        server,
                        database});
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecute(string commandstr, string userid, string password, string server, string database, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Execute", new object[] {
                        commandstr,
                        userid,
                        password,
                        server,
                        database}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReturnClass EndExecute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnClass GetValue(string selectcmd, string userid, string password, string server, string database) {
            object[] results = this.Invoke("GetValue", new object[] {
                        selectcmd,
                        userid,
                        password,
                        server,
                        database});
            return ((ReturnClass)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetValue(string selectcmd, string userid, string password, string server, string database, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetValue", new object[] {
                        selectcmd,
                        userid,
                        password,
                        server,
                        database}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReturnClass EndGetValue(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReturnClass)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnClass {
        
        private object valueField;
        
        private bool isOKField;
        
        private string messageField;
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public bool IsOK {
            get {
                return this.isOKField;
            }
            set {
                this.isOKField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
}
